version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /rails-react-app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: ikko3dayo/api
    volumes:
      - ./api:/rails-react-app
      - ./api/vendor/bundle:/rails-react-app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      WDS_SOCKET_HOST: 0.0.0.0
      WDS_SOCKET_PORT: 443
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/rails-react-app:/usr/src/app/rails-react-app
    command: sh -c "npm start"
    environment:
      WDS_SOCKET_HOST: 0.0.0.0
      WDS_SOCKET_PORT: 443
    ports:
      - '8000:3000'
      - '6006:6006'
      - '443:443'
volumes:
  postgres-data:
    driver: local
